'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class spisek

    '''<summary>
    '''loggedOK control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents loggedOK As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''loggedError control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents loggedError As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''loginMessage control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents loginMessage As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''askForLogin control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents askForLogin As Global.System.Web.UI.HtmlControls.HtmlGenericControl
End Class
