Public Class oneLogin
    Public Property id As String
    Public Property sUserName As String
    Public Property sLimitPath As String
    Public Property bAlsoPriv As Boolean
    Public Property bAlsoTajne As Boolean
    Public Property bNoLinks As Boolean = False

End Class

Public Class oneStoreFiles
    Public Property id As String
    Public Property name As String
    Public Property path As String
    Public Property isDir As Boolean
    Public Property filedate As String
    Public Property len As Long
    Public Property del As Boolean
    '"_rid": "ncweAL39oCgCAAAAAAAAAA==",
    '"_self": "dbs/ncweAA==/colls/ncweAL39oCg=/docs/ncweAL39oCgCAAAAAAAAAA==/",
    '"_etag": "\"090076f3-0000-0e00-0000-616d72e10000\"",
    '"_attachments": "attachments/",
    'Public Property _ts As Long    '1634562785
End Class

Public Class oneAudioParam

    Public Property id As String    '" "1",
    Public Property fileID As Long    '": 1296117,
    Public Property artist As String    '": "Intimate orchestra",
    Public Property title As String    '": "Song sung blue",
    Public Property album As String    '": "Various Artists",
    Public Property comment As String    '": "",
    Public Property duration As Integer ' ": 229,
    Public Property dekada As String    '": "200x    ",
    Public Property bitrate As Integer ' ": 167,
    Public Property channels As String    '": "                                ",
    Public Property sample As Integer ' ": 0,
    Public Property vbr As Integer ' ": 0,
    Public Property year As String    '": "2002      ",
    Public Property track As String    '": "12              ",
    '"_rid": "ncweAMVBuK4BAAAAAAAAAA==",
    '"_self": "dbs/ncweAA==/colls/ncweAMVBuK4=/docs/ncweAMVBuK4BAAAAAAAAAA==/",
    '"_etag": "\"2300e3d1-0000-0e00-0000-616dbc290000\"",
    '"_attachments": "attachments/",
    '"_ts": 1634581545
End Class


Public Class oneActorNames
    Public Property id As String    '": "nm0360132",
    Public Property name As String    '": "Dan Hanlon",
End Class

Public Class oneActorFilm

    Public Property filmId As String    '": "tt0047853   ",
    Public Property actorId As String    '": "nm0713421   ", <- uwaga: są spacje!
    Public Property postac As String    '": "Fernand Jérôme",
    '"id": "b4c7aa35-f7ef-4191-910d-f0d9e04af6ac",  <-- autogenerated podczas migracji SQL->Azure
    '"_rid": "ncweAIPvw84BAAAAAAAAAA==",
    '"_self": "dbs/ncweAA==/colls/ncweAIPvw84=/docs/ncweAIPvw84BAAAAAAAAAA==/",
    '"_etag": "\"50006152-0000-0e00-0000-616fba920000\"",
    '"_attachments": "attachments/",
    '"_ts": 1634712210
End Class

Public Class onePicParam
    Public Property id As String    '": "1",
    Public Property fileID As Long  ' 317914,
    Public Property width As Integer    ': 289,
    Public Property height As Integer    ' 500,
    Public Property allData As String    '": "ExifTool Version Number         : 11.89\r\nFile Name                       : bare 56f Gay Dawn.JPG\r\nDirectory                       : .\r\nFile Size                       : 41 kB\r\nFile Modification Date/Time     : 2015:06:14 15:15:18+02:00\r\nFile Access Date/Time           : 2020:01:02 18:47:42+01:00\r\nFile Creation Date/Time         : 2020:01:02 18:47:42+01:00\r\nFile Permissions                : rw-rw-rw-\r\nFile Type                       : JPEG\r\nFile Type Extension             : jpg\r\nMIME Type                       : image/jpeg\r\nJFIF Version                    : 1.01\r\nResolution Unit                 : inches\r\nX Resolution                    : 300\r\nY Resolution                    : 300\r\nComment                         : Processed By eBay With ImageMagick, z1.1.0. ||B2\r\nImage Width                     : 289\r\nImage Height                    : 500\r\nEncoding Process                : Baseline DCT, Huffman coding\r\nBits Per Sample                 : 8\r\nColor Components                : 3\r\nY Cb Cr Sub Sampling            : YCbCr4:4:4 (1 1)\r\nImage Size                      : 289x500\r\nMegapixels                      : 0.144\r\n",
    Public Property mimeType As String    '" "image/jpeg",
End Class

Public Class oneVideoParam
    Public Property id As String    '": "1",
    Public Property fileID As Long  ' 151498,
    Public Property imageSize As String    '": "464x352     ",
    Public Property duration As Integer    ' 5922,
    Public Property rok As Integer    ': 1916,
    Public Property mimeType As String    '" "video/x-msvideo         ",
    Public Property video As String    ': "|divx 25",
    Public Property audio As String    '" "|Audio () 2x44100",
    Public Property subtitle As String    '": "",
    Public Property other As String    '" "|",
End Class